# Generated by Django 6.0.5 on 2026-06-14 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='🎬', max_length=10)),
                ('banner_path', models.CharField(blank=True, max_length=500)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('superhero', 'Superhero Universe'), ('indian_epic', 'Indian Epics'), ('fantasy', 'Fantasy & Sci-Fi'), ('franchise', 'Iconic Franchise'), ('series', 'Web Series'), ('anime', 'Anime'), ('indian_cinema', 'Indian Cinema')], default='franchise', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('overview', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=500)),
                ('backdrop_path', models.CharField(blank=True, max_length=500)),
                ('release_date', models.CharField(blank=True, max_length=20)),
                ('vote_average', models.FloatField(default=0)),
                ('vote_count', models.IntegerField(default=0)),
                ('popularity', models.FloatField(default=0)),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Web Series'), ('anime', 'Anime'), ('documentary', 'Documentary')], default='movie', max_length=20)),
                ('watch_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='cinema.collection')),
            ],
            options={
                'ordering': ['-vote_average', '-popularity'],
            },
        ),
    ]
