# Generated by Django 6.0.5 on 2026-06-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
