# Generated by Django 6.0.5 on 2026-06-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vendorprofile",
            options={"verbose_name": "Vendor Profile", "verbose_name_plural": "Vendor Profiles"},
        ),
        migrations.RenameField(
            model_name="vendorprofile",
            old_name="store_description",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="vendorprofile",
            old_name="is_approved",
            new_name="is_verified",
        ),
        migrations.RemoveField(
            model_name="vendorprofile",
            name="store_name",
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="company_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="tax_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="total_sales",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vendorprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="vendorprofile",
            table="vendor_profiles",
        ),
    ]
