# Generated by Django 6.0.5 on 2026-05-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='download_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
